### ISSUE TITLE
Alarms as well as timers

### ISSUE THREAD

**Issue by craigmcgowan** [DurgNomis-drol/google_home_timers_card#8]
Is it possible to add a second sensor to the card for the alarms of a device please? Or adjust the card to accept either an alarm or a timer sensor please?
Thank you.

**Comment by DurgNomis-drol** [comment]
I will look into if it is feasible to do in this card and if i can make it look good. But it will require a lot of changes, so don't expected it to be done quick 😄

**Comment by kimonm** [comment]
A simple fix in the mean time for consideration: change the default for no timers to be something like:
const NO_TIMERS = "None set";

That way if you have a card for alarms, and none are set, it doesn't say timers.

**Comment by DurgNomis-drol** [comment]
@kimonm Thanks for your interest in this card.

I will need to change some other things to.

Would you prefer to have, a countdown for the alarm or the time at which it will fire? 

Will look into fixing this today. 😁

**Comment by kimonm** [comment]
Personally, I'd be happy just seeing the time an alarm is scheduled to fire. (That seems easier to me from an implementation standpoint, but I would be fine with either functionality.)

As a non sequitur, I can't figure out where the font for the card is set. The card doesn't match the default fonts and sizing from HA (which is fine), I'm just curious how to tweak it in the future.

**Comment by DurgNomis-drol** [comment]
About the font. The card is based around the entity card and has the exact same properties. (I just copy paste it). But if you have an issue relating fonts, please open another issue so we can keep things separated and also provide a screenshot it makes it easier for me to understand what the problem is. 😄 

I will be releasing an update later to day that should add the possibility to show both timers and alarms. I already considering to move ahead a rewrite so i can easier implement things in the future. 

Thanks for the feedback.

**Comment by DurgNomis-drol** [comment]
@kimonm @craigmcgowan 

If you can test it and report back to me that it works. [Add alarms support branch](https://github.com/DurgNomis-drol/google_home_timers_card/tree/rewrite-to-add-alarms-support). This will greatly appreciated 😄

**Comment by kimonm** [comment]
It seems to work for me:

![image](https://user-images.githubusercontent.com/40135180/111844478-5967b800-88c0-11eb-8991-143058b5367b.png)

**Comment by DurgNomis-drol** [comment]
Thanks, glad to hear that, I will merge it into master and make it the default behavior 😊
